language: ruby
cache: bundler
addons:
  firefox: 45.0
branches:
  only:
    - master
    - stable
env:
  global:
    - HEADLESS=true
    - RAILS_DB_ADAPTER=mysql2
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.1
  - 2.4.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sphinxsearch
  - echo '[mysqld]'              | sudo tee    /etc/mysql/conf.d/sort_buffer_size.cnf > /dev/null
  - echo 'sort_buffer_size = 2M' | sudo tee -a /etc/mysql/conf.d/sort_buffer_size.cnf > /dev/null
  - sudo service mysql restart
install:
  - sed -i "s/^\(gem .mysql2.\),.*$/\1/" Gemfile
  - bundle install --path vendor/bundle
  - bundle update mysql2
script:
  - bundle exec rake db:create ci --trace
matrix:
  allow_failures:
  - rvm: 2.0.0
  - rvm: 2.1.7
  - rvm: 2.3.1
  - rvm: 2.4.0
