version: '3.5'
services:
  app: &app
    build: .
    entrypoint: bin/docker-entrypoints/development/app.sh
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle/

      # mount wagons
      - ../hitobito_youth:/hitobito_youth:ro
      - ../hitobito_pbs:/hitobito_pbs:ro
    environment:
      RAILS_DB_ADAPTER: mysql2
      RAILS_DB_HOST: db
      RAILS_DB_USER: root
      RAILS_DB_PASSWORD:
      RAILS_DB_NAME: hitobito_development
      RAILS_ENV: development
    depends_on:
      - db
      - mail

  web:
    <<: *app
    entrypoint: bin/rails s -p ${PORT:-3000} -b '0.0.0.0'
    ports:
      - "${PORT:-3000}:${PORT:-3000}"

  worker:
    <<: *app
    entrypoint: bin/rake jobs:work

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

  db:
    image: mariadb
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

volumes:
  bundle:
  node_modules:

